### PR TITLE
Settings option to display text with images

### PR DESCRIPTION
**Pull request by gdsimco**
New settings option displays the question text along with the image. Fixed the scaling so it displays large images when there is no text.

With setting disabled:
python_fiJCLUhUK7

With setting enabled:
python_o3J6gM1783

### CODE REVIEW

**Review by rosslandgraf — APPROVED** [review]
LGTM, only thing I noticed is there is no restart on showtextwithimages setting change from what I can tell. Doesnt it need to restart just in case the questions were already loaded?

**Comment by gdsimco** [comment]
@rosslandgraf In the PR after this one it applies the config twice:
1. When program starts
2. Again when the game begins since the host may have changed some settings

**Comment by rosslandgraf** [comment]
> @rosslandgraf In the PR after this one it applies the config twice:
> 
> 1. When program starts
> 
> 2. Again when the game begins since the host may have changed some settings
> 
> 
> 
> See jparty/game.py in [this other pull request](https://github.com/gdsimco/JParty-with-buzzers/pull/20/files)

@gdsimco So even if the questions are preloaded like they do before the game is started (happens as soon as the game code is entered), it will still update?

**Comment by gdsimco** [comment]
@rosslandgraf Yeah the setting will still update because this only changes how the question displays. Displaying the questions is handled at runtime

**Comment by rosslandgraf** [comment]
@gdsimco ahhhh right, forgot about that. All of the data is stored prior

**Pull request merged**
